# Generated by Django 5.2.5 on 2025-08-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Укажите Telegram chat_id', max_length=50, null=True, verbose_name='Telegram chat_id'),
        ),
    ]
