# Generated by Django 5.2.5 on 2025-08-16 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Введите место выполнения привычки', max_length=255, verbose_name='Место выполнения')),
                ('time', models.TimeField(help_text='Введите время выполнения привычки', verbose_name='Время выполнения')),
                ('action', models.TextField(help_text='Введите действие привычки', verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Укажите признак приятной привычки', verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveIntegerField(default=1, help_text='Укажите периодичность выполнения привычки в днях', verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, help_text='Укажите вознаграждение за выполнение привычки', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.PositiveIntegerField(default=120, help_text='Укажите время на выполнение привычки', verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, help_text='Укажите признак публичности', verbose_name='Признак публичность')),
                ('linked_habit', models.ForeignKey(blank=True, help_text='Укажите связанную привычку', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit_tracker.habit', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(blank=True, help_text='Создатель привычки', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': ('Привычка',),
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
